// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfumeShop.Contexts;

namespace PerfumeShop.Migrations
{
    [DbContext(typeof(PerfumeShopDBContext))]
    partial class PerfumeShopDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PerfumeShop.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Nước Hoa Nam",
                            Description = "Nước hoa thường thượng nam tính",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước Hoa Nữ",
                            Description = "Quyến rũ",
                            Status = true
                        });
                });

            modelBuilder.Entity("PerfumeShop.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pictures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Trademark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            DescriptionProduct = "Chanel luôn nằm trong danh sách mẫu nước hoa đắt đỏ bán chạy nhất",
                            Pictures = "~/images/chanel.jpg",
                            Price = 18000000,
                            ProductName = "Chanel",
                            Quantity = 12,
                            Trademark = "Chanel"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            DescriptionProduct = "Shalimar là chai nước hoa được sáng tạo bởi Jacques Guerlain",
                            Pictures = "~/images/shalimar.jpg",
                            Price = 12000000,
                            ProductName = "Shalimar",
                            Quantity = 10,
                            Trademark = "Guerlain"
                        });
                });

            modelBuilder.Entity("PerfumeShop.Entities.Product", b =>
                {
                    b.HasOne("PerfumeShop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
